name: Build on request
on: [workflow_dispatch]

jobs:
  Windows:
    name: Build windows version
    runs-on: windows-2022
    timeout-minutes: 120

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup vcpkg
      run: |
        rmdir /s /q C:\vcpkg 2>nul
        git clone --depth 1 https://github.com/microsoft/vcpkg.git C:\vcpkg
        C:\vcpkg\bootstrap-vcpkg.bat -disableMetrics
      shell: cmd

    - name: Cache vcpkg packages
      uses: actions/cache@v4
      with:
        path: C:\vcpkg\installed
        key: vcpkg-x86-static-v3
        restore-keys: vcpkg-x86-static-

    - name: Install vcpkg packages
      run: |
        C:\vcpkg\vcpkg install --triplet x86-windows-static boost-iostreams boost-asio boost-beast boost-system boost-variant boost-lockfree boost-process boost-program-options boost-uuid boost-filesystem luajit glew physfs openal-soft libogg libvorbis zlib libzip bzip2 openssl
      shell: cmd

    - name: Compile otclient_dx
      timeout-minutes: 30
      run: |
        cd vc16
        MSBuild /property:Configuration=DirectX /p:BUILD_REVISION=${{github.run_number}} /p:ForceImportBeforeCppTargets=C:\vcpkg\scripts\buildsystems\msbuild\vcpkg.props
      shell: cmd

    - name: Compile otclient_gl
      timeout-minutes: 30
      run: |
        cd vc16
        MSBuild /property:Configuration=OpenGL /p:BUILD_REVISION=${{github.run_number}} /p:ForceImportBeforeCppTargets=C:\vcpkg\scripts\buildsystems\msbuild\vcpkg.props
      shell: cmd

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: Download-binaries
        path: |
          otclient_gl.exe
          otclient_dx.exe
        if-no-files-found: error
