name: Build on request
on: [workflow_dispatch]

jobs:
  Windows:
    name: Build windows version
    runs-on: windows-2022
    timeout-minutes: 120

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgGitCommitId: 'a42af01b72c28a8e1d7b48107b33e4f286a55ef6'

    - name: Install dependencies
      run: |
        $env:VCPKG_ROOT/vcpkg install --triplet x86-windows-static boost-iostreams boost-asio boost-beast boost-system boost-variant boost-lockfree boost-process boost-program-options boost-uuid boost-filesystem luajit glew physfs openal-soft libogg libvorbis zlib libzip bzip2 openssl

    - name: Compile otclient_dx
      timeout-minutes: 30
      run: |
        cd vc16
        MSBuild /property:Configuration=DirectX /p:BUILD_REVISION=${{github.run_number}} /p:VcpkgRoot="$env:VCPKG_ROOT" /p:ForceImportBeforeCppTargets="$env:VCPKG_ROOT/scripts/buildsystems/msbuild/vcpkg.props"

    - name: Compile otclient_gl
      timeout-minutes: 30
      run: |
        cd vc16
        MSBuild /property:Configuration=OpenGL /p:BUILD_REVISION=${{github.run_number}} /p:VcpkgRoot="$env:VCPKG_ROOT" /p:ForceImportBeforeCppTargets="$env:VCPKG_ROOT/scripts/buildsystems/msbuild/vcpkg.props"

    - name: Upload binaries
      uses: actions/upload-artifact@v4
      with:
        name: Download-binaries
        path: |
          otclient_gl.exe
          otclient_dx.exe
        if-no-files-found: error
